### ISSUE TITLE
Adding new files in the file tree

### ISSUE THREAD

**Issue by rainmakersumit** [stackblitz/tutorialkit#340] opened 2024-09-20 08:06 UTC
### Is your feature request related to a problem?

When creating tutorials, we may work on projects where it's beneficial to give users the option to add new files directly in the editor to keep the codebase modular. This is why this feature is particularly useful.

### Describe the solution you'd like.

The solution is simple. There can be two icons inside the editor to add new file and folder.

### Describe alternatives you've considered.

No alternative

**Comment by AriPerkkio** [comment] 2024-09-20 08:10
Duplicate of https://github.com/stackblitz/tutorialkit/issues/263.

This was implemented in https://github.com/stackblitz/tutorialkit/pull/314 but is not yet released. We are planning to release this soon though. First we need to finish couple of other features, like https://github.com/stackblitz/tutorialkit/pull/336. 

[tk-filetree-example.webm](https://github.com/user-attachments/assets/d9a664ee-1af6-4cf4-9f20-addbaa3fb381)

**Closed by AriPerkkio** 2024-09-20 08:10 UTC
